import json
import os
from urllib import response

def load_api_key():
    """Load API key from config.json file"""
    config_path = os.path.join(os.path.dirname(__file__), 'config.json')
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
            return config.get('openai_api_key')
    except FileNotFoundError:
        raise FileNotFoundError(
            "config.json not found. Please create it from config.example.json "
            "and add your OpenAI API key."
        )

API_KEY = load_api_key()


class OpenAIClient:
    """
    A client for interacting with the OpenAI API.

    Attributes:
        api_key (str): The API key for authenticating with the OpenAI API.
        model_name (str): The name of the model to use for generating responses.
        max_tokens (int): The maximum number of tokens to generate in the response.
        system_role_content (str): The content for the system role in the conversation.
        temperature (float): The randomness of the model's responses.
        top_p (float): The cumulative probability threshold for top-p sampling.
        reasoning (str): Reasoning effort level for o1/o3 models: "low", "medium", or "high".

    Methods:
        get_response(prompt: str) -> str:
            Generates a response from the OpenAI API based on the given prompt.
    """
 
    def __init__(self, api_key=API_KEY, 
                 model_name="gpt-5.5", 
          
                 system_role_content="You are a helpful assistant.",
                 reasoning="medium"): 
        """
        Initializes the OpenAIClient with the given parameters.

        Args:
            api_key (str): The API key for authenticating with the OpenAI API.
            model_name (str): The name of the model to use for generating responses. Defaults to "gpt-4o-mini".
            max_tokens (int): The maximum number of tokens to generate in the response. Defaults to 4096.
            system_role_content (str): The content for the system role in the conversation. Defaults to "You are a helpful assistant.".
            temperature (float): The randomness of the model's responses. We chose a default of 0.3
            top_p (float): The cumulative probability threshold for top-p sampling. We chosse a default of 0.6
            reasoning (str): Reasoning effort level ("low", "medium", "high"). Defaults to "low".
        """
        import openai
        openai.api_key = api_key
        self.client = openai
        self.model_name = model_name
        self.system_role_content = system_role_content
        self.reasoning = reasoning

    def get_response(self, prompt):
        """
        Generates a response from the OpenAI API based on the given prompt.

        Args:
            prompt (str): The prompt to send to the OpenAI API.

        Returns:
            str: The response generated by the OpenAI API.
        """
        try:
            params = {
                "model": self.model_name,
                "messages": [
                    {"role": "system", "content": self.system_role_content},
                    {"role": "user", "content": prompt}
                ],
                "reasoning_effort": self.reasoning
            }
            
            response = self.client.chat.completions.create(**params)
            return response.choices[0].message.content.strip()
        except Exception as e:
            print(e)

if __name__ == "__main__":
    # Example usage
    client = OpenAIClient(reasoning="medium")
    
    prompt = """
    where does  Ian Glenn use his scottish accent in his acting roles?
    """
    print("analyzing prompt...")
    response = client.get_response(prompt)
    print(response)
