INSERT INTO food_alias (food_id, alias)
VALUES
(121, 'almond'),
(121, 'almonds'),
(121, 'almond nuts'),
(121, 'almond nut'),
(121, 'amonds'),
(121, 'amond'),
(9, 'apple'),
(9, 'apples'),
(9, 'fresh apple'),
(9, 'whole apple'),
(9, 'appel'),
(9, 'aple'),
(108, 'apple juice'),
(108, 'applejuice'),
(108, 'fresh apple juice'),
(108, 'apple juce'),
(108, 'aple juice'),
(108, 'appel juice'),
(3, 'apple sauce'),
(3, 'applesauce'),
(3, 'apple puree'),
(3, 'apple sause'),
(3, 'aple sauce'),
(3, 'appel sauce'),
(15, 'avocado'),
(15, 'avocados'),
(15, 'avo'),
(15, 'fresh avocado'),
(15, 'whole avocado'),
(15, 'avacado'),
(75, 'plain bagel'),
(75, 'bagel'),
(75, 'bagels'),
(75, 'plain bagels'),
(75, 'bagle'),
(75, 'plain bagle'),
(8, 'banana'),
(8, 'bananas'),
(8, 'fresh banana'),
(8, 'whole banana'),
(8, 'bannana'),
(8, 'bananna'),
(18, 'bell pepper'),
(18, 'bell peppers'),
(18, 'sweet pepper'),
(18, 'sweet peppers'),
(18, 'capsicum'),
(18, 'bell peper'),
(35, 'black beans'),
(35, 'black bean'),
(35, 'canned black beans'),
(35, 'canned black bean'),
(35, 'tinned black beans'),
(35, 'black beens'),
(12, 'blueberries'),
(12, 'blueberry'),
(12, 'fresh blueberries'),
(12, 'fresh blueberry'),
(12, 'blue berries'),
(12, 'blueberrys'),
(56, 'bran flakes'),
(56, 'bran flake'),
(56, 'bran cereal'),
(56, 'bran flakes cereal'),
(56, 'branflakes'),
(56, 'breakfast bran flakes'),
(19, 'broccoli'),
(19, 'fresh broccoli'),
(19, 'broccoli florets'),
(19, 'broccoli floret'),
(19, 'brocoli'),
(19, 'brocolli'),
(69, 'brown rice'),
(69, 'cooked brown rice'),
(69, 'brownrice'),
(69, 'whole grain rice'),
(69, 'wholegrain rice'),
(69, 'brown rice cooked'),
(91, 'brownie'),
(91, 'brownies'),
(91, 'chocolate brownie'),
(91, 'chocolate brownies'),
(91, 'brownie square'),
(91, 'brownie squares'),
(98, 'butter'),
(98, 'butters'),
(98, 'dairy butter'),
(98, 'real butter'),
(98, 'stick butter'),
(98, 'buter'),
(89, 'vanilla cake'),
(89, 'cake'),
(89, 'vanilla cakes'),
(89, 'plain cake'),
(89, 'vanila cake'),
(89, 'vannila cake'),
(39, 'cantaloupe'),
(39, 'cantaloupes'),
(39, 'cantelope'),
(39, 'cantaloupe melon'),
(39, 'muskmelon'),
(39, 'rockmelon'),
(52, 'capn crunch'),
(52, 'cap n crunch'),
(52, 'captain crunch'),
(52, 'capn crunch cereal'),
(52, 'captain crunch cereal'),
(52, 'captn crunch'),
(20, 'carrots'),
(20, 'carrot'),
(20, 'fresh carrots'),
(20, 'fresh carrot'),
(20, 'baby carrots'),
(20, 'carrot sticks'),
(32, 'canned carrots'),
(32, 'canned carrot'),
(32, 'tinned carrots'),
(32, 'tinned carrot'),
(32, 'carrots canned'),
(32, 'can of carrots'),
(124, 'cashews'),
(124, 'cashew'),
(124, 'cashew nuts'),
(124, 'cashew nut'),
(124, 'cashewnuts'),
(124, 'kaju'),
(96, 'cheddar cheese'),
(96, 'cheddar'),
(96, 'cheese'),
(96, 'chedder cheese'),
(96, 'chedder'),
(96, 'cheddar chese'),
(48, 'cheerios'),
(48, 'cheerio'),
(48, 'cheerios cereal'),
(48, 'original cheerios'),
(48, 'plain cheerios'),
(48, 'cherios'),
(115, 'cheesecake'),
(115, 'cheesecakes'),
(115, 'cheese cake'),
(115, 'cheese cakes'),
(115, 'plain cheesecake'),
(115, 'cheescake'),
(70, 'breaded chicken cutlet'),
(70, 'chicken cutlet'),
(70, 'chicken cutlets'),
(70, 'breaded chicken cutlets'),
(70, 'breaded chicken'),
(70, 'chicken schnitzel'),
(71, 'breaded cutlet'),
(71, 'chicken breaded cutlet'),
(71, 'breaded chicken fillet'),
(71, 'breaded chicken filet'),
(71, 'crispy chicken cutlet'),
(71, 'chiken cutlet'),
(72, 'chicken thigh'),
(72, 'chicken thighs'),
(72, 'chicken thigh meat'),
(72, 'boneless chicken thigh'),
(72, 'boneless chicken thighs'),
(72, 'chiken thigh'),
(34, 'chickpeas'),
(34, 'chickpea'),
(34, 'canned chickpeas'),
(34, 'canned chickpea'),
(34, 'garbanzo beans'),
(34, 'garbanzo bean'),
(116, 'chocolate cake'),
(116, 'chocolate cakes'),
(116, 'choc cake'),
(116, 'chocolate sponge cake'),
(116, 'choclate cake'),
(116, 'chocalate cake'),
(113, 'm&ms'),
(113, 'mms'),
(113, 'm and ms'),
(113, 'mms candy'),
(113, 'chocolate mms'),
(113, 'mnms'),
(90, 'chocolate chip cookie'),
(90, 'chocolate chip cookies'),
(90, 'choc chip cookie'),
(90, 'choc chip cookies'),
(90, 'choclate chip cookie'),
(90, 'cookie'),
(57, 'cinnamon life'),
(57, 'cinnamon life cereal'),
(57, 'quaker cinnamon life'),
(57, 'quaker life cinnamon'),
(57, 'cinamon life'),
(57, 'cinnimon life'),
(53, 'cinnamon toast crunch'),
(53, 'cinnamon toast crunch cereal'),
(53, 'ctc'),
(53, 'ctc cereal'),
(53, 'cinamon toast crunch'),
(53, 'cinnamon toast cruch'),
(59, 'cocoa pebbles'),
(59, 'cocoa pebble'),
(59, 'cocoa pebbles cereal'),
(59, 'post cocoa pebbles'),
(59, 'coco pebbles'),
(59, 'coco pebbles cereal'),
(27, 'corn'),
(27, 'sweet corn'),
(27, 'sweetcorn'),
(27, 'corn kernels'),
(27, 'corn on the cob'),
(27, 'maize'),
(30, 'canned corn'),
(30, 'can of corn'),
(30, 'tinned corn'),
(30, 'canned sweet corn'),
(30, 'corn canned'),
(30, 'canned corn kernels'),
(101, 'corn chips'),
(101, 'corn chip'),
(101, 'cornchips'),
(101, 'corn snack chips'),
(101, 'fritos'),
(101, 'corn crisps'),
(46, 'corn flakes'),
(46, 'cornflake'),
(46, 'cornflakes'),
(46, 'corn flake'),
(46, 'corn flakes cereal'),
(46, 'kelloggs corn flakes'),
(110, 'corn tortilla'),
(110, 'corn tortillas'),
(110, 'tortilla'),
(110, 'tortillas'),
(110, 'maize tortilla'),
(110, 'corn tortila'),
(114, 'cream cheese'),
(114, 'plain cream cheese'),
(114, 'cream cheeses'),
(114, 'creamcheese'),
(114, 'cream cheese spread'),
(114, 'cream chese'),
(58, 'crispix'),
(58, 'crispix cereal'),
(58, 'kelloggs crispix'),
(58, 'kelloggs crispix cereal'),
(58, 'original crispix'),
(58, 'crispex'),
(17, 'cucumber'),
(17, 'cucumbers'),
(17, 'fresh cucumber'),
(17, 'cuke'),
(17, 'cukes'),
(17, 'cucumber slices'),
(112, 'dark chocolate'),
(112, '70 dark chocolate'),
(112, 'dark chocolate 70'),
(112, '70 percent dark chocolate'),
(112, '70 cacao chocolate'),
(112, 'dark choclate'),
(14, 'dates'),
(14, 'date'),
(14, 'dried dates'),
(14, 'dried date'),
(14, 'date fruit'),
(14, 'pitted dates'),
(45, 'large egg'),
(45, 'large eggs'),
(45, 'egg'),
(45, 'eggs'),
(45, 'whole egg'),
(45, 'whole eggs'),
(129, 'egg salad'),
(129, 'egg salads'),
(129, 'eggsalad'),
(129, 'egg mayo'),
(129, 'egg mayonnaise'),
(129, 'egg sald'),
(76, 'english muffin'),
(76, 'english muffins'),
(76, 'plain english muffin'),
(76, 'plain english muffins'),
(76, 'eng muffin'),
(76, 'english mufin'),
(79, 'baked french fries'),
(79, 'french fries'),
(79, 'fries'),
(79, 'baked fries'),
(79, 'oven fries'),
(79, 'oven baked fries'),
(80, 'fried french fries'),
(80, 'fried fries'),
(80, 'deep fried fries'),
(80, 'deep fried french fries'),
(80, 'french fried potatoes'),
(80, 'fast food fries'),
(50, 'frosted flakes'),
(50, 'frosted flake'),
(50, 'frosted flakes cereal'),
(50, 'kelloggs frosted flakes'),
(50, 'frostedflakes'),
(50, 'frosties'),
(88, 'frozen yogurt'),
(88, 'frozen yoghurt'),
(88, 'froyo'),
(88, 'fro yo'),
(88, 'frozen yogert'),
(88, 'frozen yougurt'),
(60, 'fruity pebbles'),
(60, 'fruity pebble'),
(60, 'fruity pebbles cereal'),
(60, 'post fruity pebbles'),
(60, 'fruit pebbles'),
(60, 'fruity pebles'),
(135, 'garden salad'),
(135, 'garden salads'),
(135, 'green salad'),
(135, 'mixed green salad'),
(135, 'tossed salad'),
(135, 'side salad'),
(26, 'garlic'),
(26, 'garlic clove'),
(26, 'garlic cloves'),
(26, 'fresh garlic'),
(26, 'raw garlic'),
(26, 'minced garlic'),
(109, 'gatorade'),
(109, 'gatorade drink'),
(109, 'gatorade sports drink'),
(109, 'sports drink'),
(109, 'gatoraide'),
(109, 'gaterade'),
(62, 'golden crisp'),
(62, 'golden crisp cereal'),
(62, 'post golden crisp'),
(62, 'super golden crisp'),
(62, 'goldencrisp'),
(62, 'golden crisps'),
